# Generated by Django 3.2.4 on 2021-07-17 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('endangered', models.BooleanField()),
                ('diet', models.CharField(choices=[('H', 'Herbivore'), ('C', 'Carnivore'), ('O', 'Omnivore')], default='H', max_length=1, verbose_name='Diet Type')),
                ('family', models.CharField(max_length=50)),
                ('species', models.CharField(max_length=50)),
                ('common_name', models.CharField(max_length=50)),
            ],
        ),
    ]
