# Generated by Django 3.2.5 on 2021-07-20 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_animal_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='endangered',
            field=models.CharField(choices=[('L', 'Least Concern'), ('N', 'Near Threatened'), ('V', 'Vulnerable'), ('E', 'Endangered'), ('C', 'Critically Endangered'), ('X', 'Extinct')], default='L', max_length=1, verbose_name='Conservation Status'),
        ),
    ]
